# .github/ISSUE_TEMPLATE/feature_request.yml
name: Feature Request
description: Suggest an improvement (hope is dangerous)
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        New features considered between 2-4 AM only.
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Explain your suffering
      placeholder: The model isn't depressed enough
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Your optimistic delusion
      placeholder: Add a mood parameter that goes from "meh" to "abyss"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other paths to disappointment
      placeholder: Therapy (too expensive)